### ISSUE TITLE
can't read property "call of undefined"  

### ISSUE THREAD

**Issue by karthik-node** [sleepycat/mapboxgl-webpack-example#2]
I am getting while running your example by cloning it Cannot read property 'call' of undefined

**Comment by sleepycat** [comment]
Things are blowing up here: `node_modules/webpack/lib/MainTemplate.js` on line 55.

I added some console.log statements to explore:

``` javascript
            "// Execute the module function",
            "console.log('Modules:', modules)",
            "console.log('ModuleId:', moduleId)",
            "console.log('modules[ModuleId]:', modules[moduleId])",
            "modules[moduleId].call(module.exports, module, module.exports, " + this.renderRequireFunctionForModule(hash, chunk, "moduleId") + ");",
```

And then I rebuilt the bundle with `./node_modules/webpack/bin/webpack.js`

modules is an array of 186 functions and it looks like one of them is not exporting anything.

On a hunch, I upgraded mapbox-gl from 0.18.0 to the current version 0.19.1 and now I get the error in #3 but the `can't read property "call" of undefined` error looks to be fixed... I'm assuming the forgotten export was added somewhere between 18.0 and 19.1.

If that goes well I will see you over in issue #3 
😄

**Comment by sleepycat** [comment]
Well with some further digging it turns out I was wrong. 
Fixing the fs.readFileSync led me back to this error again. 

It looks like `key` is undefined on line [56 of node_modules/webworkify-webpack/index.js](https://github.com/borisirota/webworkify-webpack/blob/master/index.js#L56) which blows up inside webpackBootstrapFunc when it hits `modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);` inside `__webpack_require__`.

You can see it here:

``` javascript
window = {};
var fn = (function (modules) {
        var installedModules = {};
        function __webpack_require__(moduleId) {
          if(installedModules[moduleId])
            return installedModules[moduleId].exports;
          var module = installedModules[moduleId] = {
            exports: {},
            id: moduleId,
            loaded: false
          };
          modules[moduleId].call(module.exports, module, module.exports, __webpack_require__); //moduleId here is undefined
          module.loaded = true;
          return module.exports;
        }
        __webpack_require__.m = modules;
        __webpack_require__.c = installedModules;
        __webpack_require__.oe = function(err) { throw err; };
        __webpack_require__.p = "";
        console.log(__webpack_require__)
        var f = __webpack_require__(__webpack_require__.s = undefined); //Undefined!!
        return f.default || f; // try to call default if defined to also support babel esmodule exports
    })([function (module, exports, __webpack_require__) {
```

It's not clear to me if this is due to some problem with the webpack config, and it just happens to blow up in webworkify-webpack or if it's a bug with webpack (maybe  webpack/webpack#959?) or if the problem rests with webworkify-webpack for passing undefined to `__webpack_require__` in the first place.
Thoughts?

**Comment by yinshanyang** [comment]
I found that this issue exists with `webworkify-webpack` version 1.1.0 but goes away when I rolled back to version 1.0.6

**Comment by sleepycat** [comment]
Try adding this to your webpack config and tell me if it solves it:

``` javascript
  resolve: {
    extensions: ['', '.js', '.jsx'],
    alias: {
      webworkify: 'webworkify-webpack',
      'mapbox-gl': path.resolve('./node_modules/mapbox-gl/dist/mapbox-gl.js')// <--- This!
    }
  },
```
